### ISSUE TITLE
PyPi installation missing /commands/

### ISSUE THREAD

**Issue by Chaz6** [peterthomassen/psl-dns#5]
After running `pip3 install psl_dns` the command line utilities (e.g. `psl-dns_query`) fail to run with the output `ModuleNotFoundError: No module named 'psl_dns.commands'`. This appears to be because the directory `$PYTHONPATH/psl_dns/commands` is not installed.

**Comment by peterthomassen** [comment]
Thanks for the report! Fixed in 1.0.3.
