### ISSUE TITLE
DNS update

### ISSUE THREAD

**Issue by andrewstech** [peterthomassen/psl-dns#6]
Hi I was wondering on how often the DNS updates to match the PSL? We have some domains on the PSL for a while now and the DNS is yet to include them.

`WARNING:psl:Hash mismatch! Input PSL file appears to differ from remote version.
9740 rules with 799 inconsistencies found`

Thanks Andrew

**Comment by peterthomassen** [comment]
Oops! Looks like the sync "ran away" for a while. I just did a manual sync. I'm going to check and will ensure that synchronization runs daily.

Happy to keep this open; will send an update here once it's done.

**Comment by wdhdev** [comment]
Can confirm this now works with one of the domains that was added recently.

**Comment by andrewstech** [comment]
> Oops! Looks like the sync "ran away" for a while. I just did a manual sync. I'm going to check and will ensure that synchronization runs daily.
> 
> Happy to keep this open; will send an update here once it's done.

Thank you, Can confirm that it’s updated 😀
