### ISSUE TITLE
Sync failure again?

### ISSUE THREAD

**Issue by wdhdev** [peterthomassen/psl-dns#7]
Original issue #6 

---

I've tried this package with some of the newly merged PRs on the publicsuffix/list repo, and the package does not seem to be in sync. Has it failed again like what happened with the previous issue?

**Comment by peterthomassen** [comment]
I'm sorry, there was a bug in the scheduled runner. Thank you for reporting! It's fixed now.

**Comment by wdhdev** [comment]
Thanks! Just an FYI, I believe quite a lot of fairly big companies like Cloudflare rely on this sync job as when it hasn't synced they haven't got an updated version of the PSL but after syncing they do have an updated version.

**Comment by peterthomassen** [comment]
Huh! That's very interesting and sort of unexpected, but also nice. - Can you let me know which of Cloudflare's services seemed impacted by that? (Feel free to send an email, for address see last commit.)
